- name: install the 'fail2ban'
  yum: name={{ item }} state=present
  with_items:
   - fail2ban
   - fail2ban-systemd
  tags: fail2ban
  when: "{{ fail2ban | bool }}"

- name: start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: True
  tags: fail2ban
  ignore_errors: yes
  when: "{{ fail2ban | bool }}"

- name: Create fail2ban configuration file
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  notify:
    - restart fail2ban
  tags: fail2ban
  ignore_errors: yes
  when: "{{ fail2ban | bool }}"

- name: Create fail2ban ddos configuration file
  template: src=ddos.conf.j2 dest=/etc/fail2ban/filter.d/ddos.conf
  notify:
    - restart fail2ban
  tags: fail2ban
  ignore_errors: yes
  when: "{{ fail2ban | bool }}"